/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ird.voxelidar.swing;

import fr.ird.voxelidar.engine3d.object.mesh.Attribut;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Julien
 */
public class JFrameAttributCreation extends javax.swing.JFrame {
    
    private final Map<String, Attribut> mapAttributs= new LinkedHashMap<>();
    private final ListAdapterComboboxModel model;
    

    /**
     * Creates new form JFrameAttributCreation
     */
    public JFrameAttributCreation(ListAdapterComboboxModel model) {
        
        //this.mapAttributs = mapAttributs;
        initComponents();
        
        this.model = model;
        
        jListInputParameters.setModel(model);
        
        //jListInputParameters.setListData(mapAttributs.keySet().toArray());
    }
    
    public Map<String, Attribut> getMapAttributs(){
        
        return mapAttributs;
    }

    public ListAdapterComboboxModel getModel() {
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldVariableName = new javax.swing.JTextField();
        jButtonAddInputParameter = new javax.swing.JButton();
        jTextFieldOutputParameter = new javax.swing.JTextField();
        jButtonAddOperator = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListInputParameters = new javax.swing.JList();
        jButtonAddAttribut = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListOperators = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel2.setBackground(new java.awt.Color(114, 114, 114));

        jPanel1.setBackground(new java.awt.Color(114, 114, 114));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        jTextFieldVariableName.setBackground(new java.awt.Color(180, 180, 180));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldVariableName, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldVariableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonAddInputParameter.setBackground(new java.awt.Color(85, 85, 85));
        jButtonAddInputParameter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddInputParameter.setText("Add");
        jButtonAddInputParameter.setEnabled(false);
        jButtonAddInputParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddInputParameterActionPerformed(evt);
            }
        });

        jTextFieldOutputParameter.setBackground(new java.awt.Color(180, 180, 180));
        jTextFieldOutputParameter.setBorder(javax.swing.BorderFactory.createTitledBorder("Output attribut"));

        jButtonAddOperator.setBackground(new java.awt.Color(85, 85, 85));
        jButtonAddOperator.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddOperator.setText("Add");
        jButtonAddOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddOperatorActionPerformed(evt);
            }
        });

        jListInputParameters.setBackground(new java.awt.Color(180, 180, 180));
        jListInputParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Input attributs"));
        jListInputParameters.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListInputParameters.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListInputParametersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListInputParameters);

        jButtonAddAttribut.setBackground(new java.awt.Color(85, 85, 85));
        jButtonAddAttribut.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddAttribut.setText("Add attribut");
        jButtonAddAttribut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAttributActionPerformed(evt);
            }
        });

        jListOperators.setBackground(new java.awt.Color(180, 180, 180));
        jListOperators.setBorder(javax.swing.BorderFactory.createTitledBorder("Operators"));
        jListOperators.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "+", "-", "/", "*", "^", "(", ")", "%", "abs", "acos", "asin", "atan", "cbrt", "ceil", "cos", "cosh", "exp", "floor", "log", "log2", "log10", "sin", "sinh", "sqrt", "tan", "tanh" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListOperators.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListOperators);

        jButton2.setBackground(new java.awt.Color(85, 85, 85));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldOutputParameter, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAddAttribut))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(jButtonAddInputParameter)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAddOperator))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddInputParameter)
                    .addComponent(jButtonAddOperator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOutputParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButtonAddAttribut)))
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddInputParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddInputParameterActionPerformed

        jTextFieldOutputParameter.setText(jTextFieldOutputParameter.getText()+jListInputParameters.getSelectedValue().toString());

    }//GEN-LAST:event_jButtonAddInputParameterActionPerformed

    private void jButtonAddOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddOperatorActionPerformed

        jTextFieldOutputParameter.setText(jTextFieldOutputParameter.getText()+jListOperators.getSelectedValue().toString());
    }//GEN-LAST:event_jButtonAddOperatorActionPerformed

    private void jButtonAddAttributActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAttributActionPerformed
        
        //Attribut a = new Attribut(jTextFieldVariableName.getText(), jTextFieldOutputParameter.getText(), mapAttributs.keySet());
        //mapAttributs.put(jTextFieldVariableName.getText(), a);
        ((ListAdapterComboboxModel)jListInputParameters.getModel()).addItemToModel(jTextFieldVariableName.getText(), jTextFieldOutputParameter.getText());
        //((ListAdapterComboboxModel)jListInputParameters.getModel()).dataModel.addElement(jTextFieldVariableName.getText());
        //DefaultComboBoxModel<String> attributeModel = new DefaultComboBoxModel<>();
        //jListInputParameters.setListData(mapAttributs.keySet().toArray());
        jListInputParameters.setSelectedIndex(jListInputParameters.getModel().getSize()-1);
        jListInputParameters.ensureIndexIsVisible(jListInputParameters.getModel().getSize()-1);
    }//GEN-LAST:event_jButtonAddAttributActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jListInputParametersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListInputParametersValueChanged

        if(jListInputParameters.getSelectedIndex() !=-1){
            jButtonAddInputParameter.setEnabled(true);
        }else{
            jButtonAddInputParameter.setEnabled(false);
        }
    }//GEN-LAST:event_jListInputParametersValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddAttribut;
    private javax.swing.JButton jButtonAddInputParameter;
    private javax.swing.JButton jButtonAddOperator;
    private javax.swing.JList jListInputParameters;
    private javax.swing.JList jListOperators;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldOutputParameter;
    private javax.swing.JTextField jTextFieldVariableName;
    // End of variables declaration//GEN-END:variables
}
