# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created: Wed Sep  3 12:13:15 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName(_fromUtf8("ToolBox"))
        ToolBox.resize(668, 668)
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 668, 493))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.page_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 631, 471))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.boutonLancerVisuLAS = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuLAS.setObjectName(_fromUtf8("boutonLancerVisuLAS"))
        self.gridLayout_2.addWidget(self.boutonLancerVisuLAS, 6, 0, 1, 1)
        self.boutonLancerVisuALS = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuALS.setObjectName(_fromUtf8("boutonLancerVisuALS"))
        self.gridLayout_2.addWidget(self.boutonLancerVisuALS, 7, 0, 1, 1)
        self.horizontalLayout_densite = QtGui.QHBoxLayout()
        self.horizontalLayout_densite.setObjectName(_fromUtf8("horizontalLayout_densite"))
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_densite.addWidget(self.label)
        self.label1 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.horizontalLayout_densite.addWidget(self.label1)
        self.text_seuilVisuDensite = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_seuilVisuDensite.sizePolicy().hasHeightForWidth())
        self.text_seuilVisuDensite.setSizePolicy(sizePolicy)
        self.text_seuilVisuDensite.setObjectName(_fromUtf8("text_seuilVisuDensite"))
        self.horizontalLayout_densite.addWidget(self.text_seuilVisuDensite)
        self.gridLayout_2.addLayout(self.horizontalLayout_densite, 0, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.boutonLancerVisuPoints_i = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuPoints_i.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boutonLancerVisuPoints_i.sizePolicy().hasHeightForWidth())
        self.boutonLancerVisuPoints_i.setSizePolicy(sizePolicy)
        self.boutonLancerVisuPoints_i.setObjectName(_fromUtf8("boutonLancerVisuPoints_i"))
        self.gridLayout_12.addWidget(self.boutonLancerVisuPoints_i, 6, 1, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.text_dMin_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dMin_visu.sizePolicy().hasHeightForWidth())
        self.text_dMin_visu.setSizePolicy(sizePolicy)
        self.text_dMin_visu.setObjectName(_fromUtf8("text_dMin_visu"))
        self.horizontalLayout_19.addWidget(self.text_dMin_visu)
        self.text_dMax_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dMax_visu.sizePolicy().hasHeightForWidth())
        self.text_dMax_visu.setSizePolicy(sizePolicy)
        self.text_dMax_visu.setObjectName(_fromUtf8("text_dMax_visu"))
        self.horizontalLayout_19.addWidget(self.text_dMax_visu)
        self.gridLayout_12.addLayout(self.horizontalLayout_19, 3, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_12.addWidget(self.label_56, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.text_zMax_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_zMax_visu.sizePolicy().hasHeightForWidth())
        self.text_zMax_visu.setSizePolicy(sizePolicy)
        self.text_zMax_visu.setObjectName(_fromUtf8("text_zMax_visu"))
        self.horizontalLayout_20.addWidget(self.text_zMax_visu)
        self.text_zMin_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_zMin_visu.sizePolicy().hasHeightForWidth())
        self.text_zMin_visu.setSizePolicy(sizePolicy)
        self.text_zMin_visu.setObjectName(_fromUtf8("text_zMin_visu"))
        self.horizontalLayout_20.addWidget(self.text_zMin_visu)
        self.gridLayout_12.addLayout(self.horizontalLayout_20, 4, 1, 1, 1)
        self.text_fichierPoints_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_fichierPoints_visu.sizePolicy().hasHeightForWidth())
        self.text_fichierPoints_visu.setSizePolicy(sizePolicy)
        self.text_fichierPoints_visu.setObjectName(_fromUtf8("text_fichierPoints_visu"))
        self.gridLayout_12.addWidget(self.text_fichierPoints_visu, 1, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_12.addWidget(self.label_59, 4, 0, 1, 1)
        self.boutonFichierPoints_visu = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonFichierPoints_visu.setObjectName(_fromUtf8("boutonFichierPoints_visu"))
        self.gridLayout_12.addWidget(self.boutonFichierPoints_visu, 1, 2, 1, 1)
        self.label_60 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_12.addWidget(self.label_60, 5, 0, 1, 1)
        self.label_57 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_12.addWidget(self.label_57, 2, 0, 1, 1)
        self.boutonLancerVisuPoints_o = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuPoints_o.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boutonLancerVisuPoints_o.sizePolicy().hasHeightForWidth())
        self.boutonLancerVisuPoints_o.setSizePolicy(sizePolicy)
        self.boutonLancerVisuPoints_o.setObjectName(_fromUtf8("boutonLancerVisuPoints_o"))
        self.gridLayout_12.addWidget(self.boutonLancerVisuPoints_o, 6, 2, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.text_iMin_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_iMin_visu.sizePolicy().hasHeightForWidth())
        self.text_iMin_visu.setSizePolicy(sizePolicy)
        self.text_iMin_visu.setObjectName(_fromUtf8("text_iMin_visu"))
        self.horizontalLayout_18.addWidget(self.text_iMin_visu)
        self.text_iMax_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_iMax_visu.sizePolicy().hasHeightForWidth())
        self.text_iMax_visu.setSizePolicy(sizePolicy)
        self.text_iMax_visu.setObjectName(_fromUtf8("text_iMax_visu"))
        self.horizontalLayout_18.addWidget(self.text_iMax_visu)
        self.gridLayout_12.addLayout(self.horizontalLayout_18, 2, 1, 1, 1)
        self.label_58 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_12.addWidget(self.label_58, 3, 0, 1, 1)
        self.boutonLancerVisuPoints_d = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuPoints_d.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boutonLancerVisuPoints_d.sizePolicy().hasHeightForWidth())
        self.boutonLancerVisuPoints_d.setSizePolicy(sizePolicy)
        self.boutonLancerVisuPoints_d.setObjectName(_fromUtf8("boutonLancerVisuPoints_d"))
        self.gridLayout_12.addWidget(self.boutonLancerVisuPoints_d, 6, 0, 1, 1)
        self.text_proportionPoints_visu = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_proportionPoints_visu.sizePolicy().hasHeightForWidth())
        self.text_proportionPoints_visu.setSizePolicy(sizePolicy)
        self.text_proportionPoints_visu.setObjectName(_fromUtf8("text_proportionPoints_visu"))
        self.gridLayout_12.addWidget(self.text_proportionPoints_visu, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_12, 5, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.boutonLancerVisuDensite_distribution = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuDensite_distribution.setObjectName(_fromUtf8("boutonLancerVisuDensite_distribution"))
        self.gridLayout.addWidget(self.boutonLancerVisuDensite_distribution, 0, 2, 1, 1)
        self.boutonLancerVisuDensite_3classes = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuDensite_3classes.setObjectName(_fromUtf8("boutonLancerVisuDensite_3classes"))
        self.gridLayout.addWidget(self.boutonLancerVisuDensite_3classes, 0, 1, 1, 1)
        self.boutonLancerVisuDensite_profil = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuDensite_profil.setObjectName(_fromUtf8("boutonLancerVisuDensite_profil"))
        self.gridLayout.addWidget(self.boutonLancerVisuDensite_profil, 0, 3, 1, 1)
        self.boutonLancerVisuDensite = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuDensite.setObjectName(_fromUtf8("boutonLancerVisuDensite"))
        self.gridLayout.addWidget(self.boutonLancerVisuDensite, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.boutonLancerVisuNApres = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuNApres.setObjectName(_fromUtf8("boutonLancerVisuNApres"))
        self.gridLayout_3.addWidget(self.boutonLancerVisuNApres, 0, 2, 1, 1)
        self.boutonLancerVisuNdedans = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuNdedans.setObjectName(_fromUtf8("boutonLancerVisuNdedans"))
        self.gridLayout_3.addWidget(self.boutonLancerVisuNdedans, 0, 0, 1, 1)
        self.boutonLancerVisuNTotal = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.boutonLancerVisuNTotal.setObjectName(_fromUtf8("boutonLancerVisuNTotal"))
        self.gridLayout_3.addWidget(self.boutonLancerVisuNTotal, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        ToolBox.addItem(self.page_4, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 668, 493))
        self.page.setObjectName(_fromUtf8("page"))
        self.layoutWidget = QtGui.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 651, 146))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_17 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.text_fichierPoints_filtrer = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_fichierPoints_filtrer.sizePolicy().hasHeightForWidth())
        self.text_fichierPoints_filtrer.setSizePolicy(sizePolicy)
        self.text_fichierPoints_filtrer.setObjectName(_fromUtf8("text_fichierPoints_filtrer"))
        self.gridLayout_17.addWidget(self.text_fichierPoints_filtrer, 0, 1, 1, 1)
        self.label_61 = QtGui.QLabel(self.layoutWidget)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_17.addWidget(self.label_61, 0, 0, 1, 1)
        self.text_fichierMNT = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_fichierMNT.sizePolicy().hasHeightForWidth())
        self.text_fichierMNT.setSizePolicy(sizePolicy)
        self.text_fichierMNT.setObjectName(_fromUtf8("text_fichierMNT"))
        self.gridLayout_17.addWidget(self.text_fichierMNT, 1, 1, 1, 1)
        self.boutonFichierPoints = QtGui.QPushButton(self.layoutWidget)
        self.boutonFichierPoints.setObjectName(_fromUtf8("boutonFichierPoints"))
        self.gridLayout_17.addWidget(self.boutonFichierPoints, 0, 2, 1, 1)
        self.label_62 = QtGui.QLabel(self.layoutWidget)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_17.addWidget(self.label_62, 1, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.text_altitudeMoy = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_altitudeMoy.sizePolicy().hasHeightForWidth())
        self.text_altitudeMoy.setSizePolicy(sizePolicy)
        self.text_altitudeMoy.setObjectName(_fromUtf8("text_altitudeMoy"))
        self.horizontalLayout_23.addWidget(self.text_altitudeMoy)
        self.text_dz = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dz.sizePolicy().hasHeightForWidth())
        self.text_dz.setSizePolicy(sizePolicy)
        self.text_dz.setObjectName(_fromUtf8("text_dz"))
        self.horizontalLayout_23.addWidget(self.text_dz)
        self.gridLayout_17.addLayout(self.horizontalLayout_23, 2, 1, 1, 1)
        self.filtrerPointSurCoucheDZ = QtGui.QPushButton(self.layoutWidget)
        self.filtrerPointSurCoucheDZ.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtrerPointSurCoucheDZ.sizePolicy().hasHeightForWidth())
        self.filtrerPointSurCoucheDZ.setSizePolicy(sizePolicy)
        self.filtrerPointSurCoucheDZ.setObjectName(_fromUtf8("filtrerPointSurCoucheDZ"))
        self.gridLayout_17.addWidget(self.filtrerPointSurCoucheDZ, 3, 1, 1, 1)
        self.label_64 = QtGui.QLabel(self.layoutWidget)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_17.addWidget(self.label_64, 2, 0, 1, 1)
        self.boutonFichierMNT = QtGui.QPushButton(self.layoutWidget)
        self.boutonFichierMNT.setObjectName(_fromUtf8("boutonFichierMNT"))
        self.gridLayout_17.addWidget(self.boutonFichierMNT, 1, 2, 1, 1)
        self.gridLayout_17.setColumnStretch(1, 1)
        self.boutonCalculerMNT = QtGui.QPushButton(self.page)
        self.boutonCalculerMNT.setEnabled(True)
        self.boutonCalculerMNT.setGeometry(QtCore.QRect(150, 210, 410, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boutonCalculerMNT.sizePolicy().hasHeightForWidth())
        self.boutonCalculerMNT.setSizePolicy(sizePolicy)
        self.boutonCalculerMNT.setObjectName(_fromUtf8("boutonCalculerMNT"))
        ToolBox.addItem(self.page, _fromUtf8(""))
        self.page1 = QtGui.QWidget()
        self.page1.setGeometry(QtCore.QRect(0, 0, 668, 493))
        self.page1.setObjectName(_fromUtf8("page1"))
        self.layoutWidget_2 = QtGui.QWidget(self.page1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 10, 538, 187))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_63 = QtGui.QLabel(self.layoutWidget_2)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_18.addWidget(self.label_63, 0, 0, 1, 1)
        self.text_fichierPoints_filtrer_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_fichierPoints_filtrer_2.sizePolicy().hasHeightForWidth())
        self.text_fichierPoints_filtrer_2.setSizePolicy(sizePolicy)
        self.text_fichierPoints_filtrer_2.setObjectName(_fromUtf8("text_fichierPoints_filtrer_2"))
        self.gridLayout_18.addWidget(self.text_fichierPoints_filtrer_2, 0, 1, 1, 1)
        self.boutonFichierPoints_filtrer = QtGui.QPushButton(self.layoutWidget_2)
        self.boutonFichierPoints_filtrer.setObjectName(_fromUtf8("boutonFichierPoints_filtrer"))
        self.gridLayout_18.addWidget(self.boutonFichierPoints_filtrer, 0, 2, 1, 1)
        self.label_65 = QtGui.QLabel(self.layoutWidget_2)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_18.addWidget(self.label_65, 1, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.text_iMin_visu_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_iMin_visu_2.sizePolicy().hasHeightForWidth())
        self.text_iMin_visu_2.setSizePolicy(sizePolicy)
        self.text_iMin_visu_2.setObjectName(_fromUtf8("text_iMin_visu_2"))
        self.horizontalLayout_21.addWidget(self.text_iMin_visu_2)
        self.text_iMax_visu_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_iMax_visu_2.sizePolicy().hasHeightForWidth())
        self.text_iMax_visu_2.setSizePolicy(sizePolicy)
        self.text_iMax_visu_2.setObjectName(_fromUtf8("text_iMax_visu_2"))
        self.horizontalLayout_21.addWidget(self.text_iMax_visu_2)
        self.gridLayout_18.addLayout(self.horizontalLayout_21, 1, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.layoutWidget_2)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_18.addWidget(self.label_66, 2, 0, 1, 1)
        self.label_67 = QtGui.QLabel(self.layoutWidget_2)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_18.addWidget(self.label_67, 3, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.text_dMin_visu_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dMin_visu_2.sizePolicy().hasHeightForWidth())
        self.text_dMin_visu_2.setSizePolicy(sizePolicy)
        self.text_dMin_visu_2.setObjectName(_fromUtf8("text_dMin_visu_2"))
        self.horizontalLayout_22.addWidget(self.text_dMin_visu_2)
        self.text_dMax_visu_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dMax_visu_2.sizePolicy().hasHeightForWidth())
        self.text_dMax_visu_2.setSizePolicy(sizePolicy)
        self.text_dMax_visu_2.setObjectName(_fromUtf8("text_dMax_visu_2"))
        self.horizontalLayout_22.addWidget(self.text_dMax_visu_2)
        self.gridLayout_18.addLayout(self.horizontalLayout_22, 2, 1, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.text_zMin_visu_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_zMin_visu_2.sizePolicy().hasHeightForWidth())
        self.text_zMin_visu_2.setSizePolicy(sizePolicy)
        self.text_zMin_visu_2.setObjectName(_fromUtf8("text_zMin_visu_2"))
        self.horizontalLayout_24.addWidget(self.text_zMin_visu_2)
        self.text_zMax_visu_2 = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_zMax_visu_2.sizePolicy().hasHeightForWidth())
        self.text_zMax_visu_2.setSizePolicy(sizePolicy)
        self.text_zMax_visu_2.setObjectName(_fromUtf8("text_zMax_visu_2"))
        self.horizontalLayout_24.addWidget(self.text_zMax_visu_2)
        self.gridLayout_18.addLayout(self.horizontalLayout_24, 3, 1, 1, 1)
        self.boutonFiltrerPoints = QtGui.QPushButton(self.layoutWidget_2)
        self.boutonFiltrerPoints.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boutonFiltrerPoints.sizePolicy().hasHeightForWidth())
        self.boutonFiltrerPoints.setSizePolicy(sizePolicy)
        self.boutonFiltrerPoints.setObjectName(_fromUtf8("boutonFiltrerPoints"))
        self.gridLayout_18.addWidget(self.boutonFiltrerPoints, 4, 1, 1, 1)
        self.gridLayout_18.setColumnStretch(1, 1)
        ToolBox.addItem(self.page1, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 668, 493))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.boutonProjeterDensite = QtGui.QPushButton(self.page_3)
        self.boutonProjeterDensite.setGeometry(QtCore.QRect(160, 10, 329, 31))
        self.boutonProjeterDensite.setObjectName(_fromUtf8("boutonProjeterDensite"))
        self.layoutWidget_3 = QtGui.QWidget(self.page_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 70, 542, 185))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_19 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_68 = QtGui.QLabel(self.layoutWidget_3)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_19.addWidget(self.label_68, 3, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.layoutWidget_3)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_19.addWidget(self.label_69, 2, 0, 1, 1)
        self.boutonProjeterPoints = QtGui.QPushButton(self.layoutWidget_3)
        self.boutonProjeterPoints.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boutonProjeterPoints.sizePolicy().hasHeightForWidth())
        self.boutonProjeterPoints.setSizePolicy(sizePolicy)
        self.boutonProjeterPoints.setObjectName(_fromUtf8("boutonProjeterPoints"))
        self.gridLayout_19.addWidget(self.boutonProjeterPoints, 4, 1, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.text_yMin_projeter = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_yMin_projeter.sizePolicy().hasHeightForWidth())
        self.text_yMin_projeter.setSizePolicy(sizePolicy)
        self.text_yMin_projeter.setObjectName(_fromUtf8("text_yMin_projeter"))
        self.horizontalLayout_25.addWidget(self.text_yMin_projeter)
        self.text_yMax_projeter = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_yMax_projeter.sizePolicy().hasHeightForWidth())
        self.text_yMax_projeter.setSizePolicy(sizePolicy)
        self.text_yMax_projeter.setObjectName(_fromUtf8("text_yMax_projeter"))
        self.horizontalLayout_25.addWidget(self.text_yMax_projeter)
        self.gridLayout_19.addLayout(self.horizontalLayout_25, 2, 1, 1, 1)
        self.text_resolution_projeter = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_resolution_projeter.sizePolicy().hasHeightForWidth())
        self.text_resolution_projeter.setSizePolicy(sizePolicy)
        self.text_resolution_projeter.setObjectName(_fromUtf8("text_resolution_projeter"))
        self.gridLayout_19.addWidget(self.text_resolution_projeter, 3, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.layoutWidget_3)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_19.addWidget(self.label_70, 1, 0, 1, 1)
        self.label_71 = QtGui.QLabel(self.layoutWidget_3)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_19.addWidget(self.label_71, 0, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.text_xMin_projeter = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_xMin_projeter.sizePolicy().hasHeightForWidth())
        self.text_xMin_projeter.setSizePolicy(sizePolicy)
        self.text_xMin_projeter.setObjectName(_fromUtf8("text_xMin_projeter"))
        self.horizontalLayout_26.addWidget(self.text_xMin_projeter)
        self.text_xMax_projeter = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_xMax_projeter.sizePolicy().hasHeightForWidth())
        self.text_xMax_projeter.setSizePolicy(sizePolicy)
        self.text_xMax_projeter.setObjectName(_fromUtf8("text_xMax_projeter"))
        self.horizontalLayout_26.addWidget(self.text_xMax_projeter)
        self.gridLayout_19.addLayout(self.horizontalLayout_26, 1, 1, 1, 1)
        self.boutonFichierPoints_projeter = QtGui.QPushButton(self.layoutWidget_3)
        self.boutonFichierPoints_projeter.setObjectName(_fromUtf8("boutonFichierPoints_projeter"))
        self.gridLayout_19.addWidget(self.boutonFichierPoints_projeter, 0, 2, 1, 1)
        self.text_fichierPoints_projeter = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_fichierPoints_projeter.sizePolicy().hasHeightForWidth())
        self.text_fichierPoints_projeter.setSizePolicy(sizePolicy)
        self.text_fichierPoints_projeter.setObjectName(_fromUtf8("text_fichierPoints_projeter"))
        self.gridLayout_19.addWidget(self.text_fichierPoints_projeter, 0, 1, 1, 1)
        self.gridLayout_19.setColumnStretch(1, 1)
        self.line_2 = QtGui.QFrame(self.page_3)
        self.line_2.setGeometry(QtCore.QRect(70, 50, 481, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        ToolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 668, 493))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.page_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 531, 131))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.boutonfusionPoints = QtGui.QPushButton(self.verticalLayoutWidget)
        self.boutonfusionPoints.setObjectName(_fromUtf8("boutonfusionPoints"))
        self.verticalLayout.addWidget(self.boutonfusionPoints)
        self.boutonfusionDensite = QtGui.QPushButton(self.verticalLayoutWidget)
        self.boutonfusionDensite.setObjectName(_fromUtf8("boutonfusionDensite"))
        self.verticalLayout.addWidget(self.boutonfusionDensite)
        self.boutonfusionDensite_pondere = QtGui.QPushButton(self.verticalLayoutWidget)
        self.boutonfusionDensite_pondere.setObjectName(_fromUtf8("boutonfusionDensite_pondere"))
        self.verticalLayout.addWidget(self.boutonfusionDensite_pondere)
        ToolBox.addItem(self.page_2, _fromUtf8(""))

        self.retranslateUi(ToolBox)
        ToolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        ToolBox.setWindowTitle(QtGui.QApplication.translate("ToolBox", "ToolBox", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuLAS.setText(QtGui.QApplication.translate("ToolBox", "visualiser fichier LAS", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuALS.setText(QtGui.QApplication.translate("ToolBox", "visualiser fichier de points ALS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ToolBox", "Densité : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("ToolBox", "Seuil (nombre tirs minimum par voxel) : ", None, QtGui.QApplication.UnicodeUTF8))
        self.text_seuilVisuDensite.setText(QtGui.QApplication.translate("ToolBox", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuPoints_i.setText(QtGui.QApplication.translate("ToolBox", "visualiser points extraits (intensite)", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dMin_visu.setText(QtGui.QApplication.translate("ToolBox", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dMax_visu.setText(QtGui.QApplication.translate("ToolBox", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("ToolBox", "fichier de points", None, QtGui.QApplication.UnicodeUTF8))
        self.text_zMax_visu.setText(QtGui.QApplication.translate("ToolBox", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.text_zMin_visu.setText(QtGui.QApplication.translate("ToolBox", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("ToolBox", "Altitude min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFichierPoints_visu.setText(QtGui.QApplication.translate("ToolBox", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("ToolBox", "proportion de points ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("ToolBox", "Intensite min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuPoints_o.setText(QtGui.QApplication.translate("ToolBox", "ordre", None, QtGui.QApplication.UnicodeUTF8))
        self.text_iMin_visu.setText(QtGui.QApplication.translate("ToolBox", "-100", None, QtGui.QApplication.UnicodeUTF8))
        self.text_iMax_visu.setText(QtGui.QApplication.translate("ToolBox", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("ToolBox", "Deviation min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuPoints_d.setText(QtGui.QApplication.translate("ToolBox", "deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.text_proportionPoints_visu.setToolTip(QtGui.QApplication.translate("ToolBox", "affiche (1/ valeur) points du fichier de points. 1 pour visualiser tous les points (jusqu\'a une limite de 3 millions de points)", None, QtGui.QApplication.UnicodeUTF8))
        self.text_proportionPoints_visu.setText(QtGui.QApplication.translate("ToolBox", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuDensite_distribution.setText(QtGui.QApplication.translate("ToolBox", "Histogramme", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuDensite_3classes.setText(QtGui.QApplication.translate("ToolBox", "densite 3D - 3 classes", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuDensite_profil.setText(QtGui.QApplication.translate("ToolBox", "Profil de LAI", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuDensite.setText(QtGui.QApplication.translate("ToolBox", "densite 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ToolBox", "Points :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ToolBox", "Maille :", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuNApres.setText(QtGui.QApplication.translate("ToolBox", "N apres", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuNdedans.setText(QtGui.QApplication.translate("ToolBox", "N dedans", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLancerVisuNTotal.setText(QtGui.QApplication.translate("ToolBox", "N entrant (total)", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.page_4), QtGui.QApplication.translate("ToolBox", "Visualiser", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("ToolBox", "fichier de points", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFichierPoints.setText(QtGui.QApplication.translate("ToolBox", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("ToolBox", "Fichier MNT (option)", None, QtGui.QApplication.UnicodeUTF8))
        self.text_altitudeMoy.setText(QtGui.QApplication.translate("ToolBox", "1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dz.setText(QtGui.QApplication.translate("ToolBox", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.filtrerPointSurCoucheDZ.setText(QtGui.QApplication.translate("ToolBox", "Extraire points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("ToolBox", "Altitude moy / delta Z", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFichierMNT.setText(QtGui.QApplication.translate("ToolBox", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonCalculerMNT.setText(QtGui.QApplication.translate("ToolBox", "Calculer MNT depuis maillage", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.page), QtGui.QApplication.translate("ToolBox", "Extraire Points sur couche DZ avec MNT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("ToolBox", "fichier de points", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFichierPoints_filtrer.setText(QtGui.QApplication.translate("ToolBox", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("ToolBox", "Intensite min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.text_iMin_visu_2.setText(QtGui.QApplication.translate("ToolBox", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.text_iMax_visu_2.setText(QtGui.QApplication.translate("ToolBox", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("ToolBox", "Deviation min/max     ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("ToolBox", "Altitude min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dMin_visu_2.setText(QtGui.QApplication.translate("ToolBox", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dMax_visu_2.setText(QtGui.QApplication.translate("ToolBox", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.text_zMin_visu_2.setText(QtGui.QApplication.translate("ToolBox", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.text_zMax_visu_2.setText(QtGui.QApplication.translate("ToolBox", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFiltrerPoints.setText(QtGui.QApplication.translate("ToolBox", "Filtrer points", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.page1), QtGui.QApplication.translate("ToolBox", "Filtrage", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonProjeterDensite.setText(QtGui.QApplication.translate("ToolBox", "Projeter fichier de densite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("ToolBox", "resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("ToolBox", "Limites Y (min / max)  ", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonProjeterPoints.setText(QtGui.QApplication.translate("ToolBox", "Projeter points", None, QtGui.QApplication.UnicodeUTF8))
        self.text_yMin_projeter.setText(QtGui.QApplication.translate("ToolBox", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_yMax_projeter.setText(QtGui.QApplication.translate("ToolBox", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_resolution_projeter.setToolTip(QtGui.QApplication.translate("ToolBox", "affiche (1/ valeur) points du fichier de points. 1 pour visualiser tous les points (jusqu\'a une limite de 3 millions de points)", None, QtGui.QApplication.UnicodeUTF8))
        self.text_resolution_projeter.setText(QtGui.QApplication.translate("ToolBox", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("ToolBox", "limites X (min / max)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("ToolBox", "fichier de points", None, QtGui.QApplication.UnicodeUTF8))
        self.text_xMin_projeter.setText(QtGui.QApplication.translate("ToolBox", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_xMax_projeter.setText(QtGui.QApplication.translate("ToolBox", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFichierPoints_projeter.setText(QtGui.QApplication.translate("ToolBox", "...", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.page_3), QtGui.QApplication.translate("ToolBox", "Projection 2D", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonfusionPoints.setText(QtGui.QApplication.translate("ToolBox", "Fusionner fichiers points", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonfusionDensite.setText(QtGui.QApplication.translate("ToolBox", "Fusionner fichiers densites (sans ponderation)", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonfusionDensite_pondere.setText(QtGui.QApplication.translate("ToolBox", "Fusionner fichiers densites (avec ponderation par angle solide)", None, QtGui.QApplication.UnicodeUTF8))
        ToolBox.setItemText(ToolBox.indexOf(self.page_2), QtGui.QApplication.translate("ToolBox", "Fusion de fichiers", None, QtGui.QApplication.UnicodeUTF8))

