# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voxelisation2.ui'
#
# Created: Thu Aug 28 10:43:30 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(750, 960)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frame)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.tabPrincipal = QtGui.QTabWidget(self.frame)
        self.tabPrincipal.setAccessibleName(_fromUtf8(""))
        self.tabPrincipal.setUsesScrollButtons(False)
        self.tabPrincipal.setObjectName(_fromUtf8("tabPrincipal"))
        self.tabConfig = QtGui.QWidget()
        self.tabConfig.setObjectName(_fromUtf8("tabConfig"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabConfig)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.text_repertoireDefaut = QtGui.QLineEdit(self.tabConfig)
        self.text_repertoireDefaut.setObjectName(_fromUtf8("text_repertoireDefaut"))
        self.gridLayout_10.addWidget(self.text_repertoireDefaut, 0, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.tabConfig)
        self.label_37.setEnabled(True)
        self.label_37.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_10.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.tabConfig)
        self.label_34.setEnabled(True)
        self.label_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_10.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.tabConfig)
        self.label_36.setEnabled(True)
        self.label_36.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_10.addWidget(self.label_36, 1, 0, 1, 1)
        self.boutonRepertoireDefaut = QtGui.QPushButton(self.tabConfig)
        self.boutonRepertoireDefaut.setObjectName(_fromUtf8("boutonRepertoireDefaut"))
        self.gridLayout_10.addWidget(self.boutonRepertoireDefaut, 0, 2, 1, 1)
        self.boutonCheminExec = QtGui.QPushButton(self.tabConfig)
        self.boutonCheminExec.setObjectName(_fromUtf8("boutonCheminExec"))
        self.gridLayout_10.addWidget(self.boutonCheminExec, 1, 2, 1, 1)
        self.text_cheminLog = QtGui.QLineEdit(self.tabConfig)
        self.text_cheminLog.setObjectName(_fromUtf8("text_cheminLog"))
        self.gridLayout_10.addWidget(self.text_cheminLog, 2, 1, 1, 1)
        self.boutonLog = QtGui.QPushButton(self.tabConfig)
        self.boutonLog.setObjectName(_fromUtf8("boutonLog"))
        self.gridLayout_10.addWidget(self.boutonLog, 2, 2, 1, 1)
        self.text_cheminExec = QtGui.QLineEdit(self.tabConfig)
        self.text_cheminExec.setObjectName(_fromUtf8("text_cheminExec"))
        self.gridLayout_10.addWidget(self.text_cheminExec, 1, 1, 1, 1)
        self.gridLayout_10.setColumnStretch(1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_10)
        self.textConsole = QtGui.QTextEdit(self.tabConfig)
        self.textConsole.setObjectName(_fromUtf8("textConsole"))
        self.verticalLayout_4.addWidget(self.textConsole)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabPrincipal.addTab(self.tabConfig, _fromUtf8(""))
        self.tabProperties = QtGui.QWidget()
        self.tabProperties.setObjectName(_fromUtf8("tabProperties"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabProperties)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_11.setSpacing(5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.combo_box_listeTypeExtraction = QtGui.QComboBox(self.tabProperties)
        self.combo_box_listeTypeExtraction.setObjectName(_fromUtf8("combo_box_listeTypeExtraction"))
        self.combo_box_listeTypeExtraction.addItem(_fromUtf8(""))
        self.combo_box_listeTypeExtraction.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.combo_box_listeTypeExtraction, 2, 1, 1, 1)
        self.combo_box_listeScan = QtGui.QComboBox(self.tabProperties)
        self.combo_box_listeScan.setObjectName(_fromUtf8("combo_box_listeScan"))
        self.combo_box_listeScan.addItem(_fromUtf8(""))
        self.combo_box_listeScan.addItem(_fromUtf8(""))
        self.combo_box_listeScan.addItem(_fromUtf8(""))
        self.combo_box_listeScan.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.combo_box_listeScan, 1, 1, 1, 1)
        self.combo_box_Mode = QtGui.QComboBox(self.tabProperties)
        self.combo_box_Mode.setObjectName(_fromUtf8("combo_box_Mode"))
        self.combo_box_Mode.addItem(_fromUtf8(""))
        self.combo_box_Mode.addItem(_fromUtf8(""))
        self.combo_box_Mode.addItem(_fromUtf8(""))
        self.combo_box_Mode.addItem(_fromUtf8(""))
        self.combo_box_Mode.addItem(_fromUtf8(""))
        self.combo_box_Mode.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.combo_box_Mode, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.tabProperties)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_11.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.tabProperties)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_11.addWidget(self.label_44, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.tabProperties)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_11.addWidget(self.label_45, 3, 0, 1, 1)
        self.combo_box_listeTypeMultiEcho = QtGui.QComboBox(self.tabProperties)
        self.combo_box_listeTypeMultiEcho.setObjectName(_fromUtf8("combo_box_listeTypeMultiEcho"))
        self.combo_box_listeTypeMultiEcho.addItem(_fromUtf8(""))
        self.combo_box_listeTypeMultiEcho.addItem(_fromUtf8(""))
        self.combo_box_listeTypeMultiEcho.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.combo_box_listeTypeMultiEcho, 3, 1, 1, 1)
        self.text_projRiegl = QtGui.QLineEdit(self.tabProperties)
        self.text_projRiegl.setObjectName(_fromUtf8("text_projRiegl"))
        self.gridLayout_11.addWidget(self.text_projRiegl, 4, 1, 1, 1)
        self.boutonProjetRiegl = QtGui.QPushButton(self.tabProperties)
        self.boutonProjetRiegl.setObjectName(_fromUtf8("boutonProjetRiegl"))
        self.gridLayout_11.addWidget(self.boutonProjetRiegl, 4, 2, 1, 1)
        self.text_dossierOutput = QtGui.QLineEdit(self.tabProperties)
        self.text_dossierOutput.setObjectName(_fromUtf8("text_dossierOutput"))
        self.gridLayout_11.addWidget(self.text_dossierOutput, 5, 1, 1, 1)
        self.boutonDossierOutput = QtGui.QPushButton(self.tabProperties)
        self.boutonDossierOutput.setObjectName(_fromUtf8("boutonDossierOutput"))
        self.gridLayout_11.addWidget(self.boutonDossierOutput, 5, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.tabProperties)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_11.addWidget(self.label_46, 6, 0, 1, 1)
        self.combo_box_maillage = QtGui.QComboBox(self.tabProperties)
        self.combo_box_maillage.setObjectName(_fromUtf8("combo_box_maillage"))
        self.combo_box_maillage.addItem(_fromUtf8(""))
        self.combo_box_maillage.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.combo_box_maillage, 6, 1, 1, 1)
        self.label_47 = QtGui.QLabel(self.tabProperties)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_11.addWidget(self.label_47, 9, 0, 1, 1)
        self.text_Resolution = QtGui.QLineEdit(self.tabProperties)
        self.text_Resolution.setObjectName(_fromUtf8("text_Resolution"))
        self.gridLayout_11.addWidget(self.text_Resolution, 9, 1, 1, 1)
        self.boutonverifier = QtGui.QPushButton(self.tabProperties)
        self.boutonverifier.setObjectName(_fromUtf8("boutonverifier"))
        self.gridLayout_11.addWidget(self.boutonverifier, 9, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.tabProperties)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_11.addWidget(self.label_40, 10, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.tabProperties)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_11.addWidget(self.label_41, 11, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.tabProperties)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_11.addWidget(self.label_42, 5, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.tabProperties)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_11.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.tabProperties)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_11.addWidget(self.label_39, 4, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.text_Xmin = QtGui.QLineEdit(self.tabProperties)
        self.text_Xmin.setObjectName(_fromUtf8("text_Xmin"))
        self.horizontalLayout_14.addWidget(self.text_Xmin)
        self.text_Ymin = QtGui.QLineEdit(self.tabProperties)
        self.text_Ymin.setObjectName(_fromUtf8("text_Ymin"))
        self.horizontalLayout_14.addWidget(self.text_Ymin)
        self.text_Zmin = QtGui.QLineEdit(self.tabProperties)
        self.text_Zmin.setObjectName(_fromUtf8("text_Zmin"))
        self.horizontalLayout_14.addWidget(self.text_Zmin)
        self.gridLayout_11.addLayout(self.horizontalLayout_14, 10, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.text_Xmax = QtGui.QLineEdit(self.tabProperties)
        self.text_Xmax.setObjectName(_fromUtf8("text_Xmax"))
        self.horizontalLayout_15.addWidget(self.text_Xmax)
        self.text_Ymax = QtGui.QLineEdit(self.tabProperties)
        self.text_Ymax.setObjectName(_fromUtf8("text_Ymax"))
        self.horizontalLayout_15.addWidget(self.text_Ymax)
        self.text_Zmax = QtGui.QLineEdit(self.tabProperties)
        self.text_Zmax.setObjectName(_fromUtf8("text_Zmax"))
        self.horizontalLayout_15.addWidget(self.text_Zmax)
        self.gridLayout_11.addLayout(self.horizontalLayout_15, 11, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.tabProperties)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_11.addWidget(self.label_48, 12, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.cbox_iFiltre = QtGui.QCheckBox(self.tabProperties)
        self.cbox_iFiltre.setText(_fromUtf8(""))
        self.cbox_iFiltre.setObjectName(_fromUtf8("cbox_iFiltre"))
        self.horizontalLayout_16.addWidget(self.cbox_iFiltre)
        self.text_iMin = QtGui.QLineEdit(self.tabProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_iMin.sizePolicy().hasHeightForWidth())
        self.text_iMin.setSizePolicy(sizePolicy)
        self.text_iMin.setObjectName(_fromUtf8("text_iMin"))
        self.horizontalLayout_16.addWidget(self.text_iMin)
        self.text_iMax = QtGui.QLineEdit(self.tabProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_iMax.sizePolicy().hasHeightForWidth())
        self.text_iMax.setSizePolicy(sizePolicy)
        self.text_iMax.setObjectName(_fromUtf8("text_iMax"))
        self.horizontalLayout_16.addWidget(self.text_iMax)
        self.gridLayout_11.addLayout(self.horizontalLayout_16, 12, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.tabProperties)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_11.addWidget(self.label_49, 13, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.cbox_dFiltre = QtGui.QCheckBox(self.tabProperties)
        self.cbox_dFiltre.setText(_fromUtf8(""))
        self.cbox_dFiltre.setObjectName(_fromUtf8("cbox_dFiltre"))
        self.horizontalLayout_17.addWidget(self.cbox_dFiltre)
        self.text_dMin = QtGui.QLineEdit(self.tabProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dMin.sizePolicy().hasHeightForWidth())
        self.text_dMin.setSizePolicy(sizePolicy)
        self.text_dMin.setObjectName(_fromUtf8("text_dMin"))
        self.horizontalLayout_17.addWidget(self.text_dMin)
        self.text_dMax = QtGui.QLineEdit(self.tabProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_dMax.sizePolicy().hasHeightForWidth())
        self.text_dMax.setSizePolicy(sizePolicy)
        self.text_dMax.setObjectName(_fromUtf8("text_dMax"))
        self.horizontalLayout_17.addWidget(self.text_dMax)
        self.gridLayout_11.addLayout(self.horizontalLayout_17, 13, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.tabProperties)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_11.addWidget(self.label_50, 15, 0, 1, 1)
        self.text_nomSortieDensite = QtGui.QLineEdit(self.tabProperties)
        self.text_nomSortieDensite.setText(_fromUtf8(""))
        self.text_nomSortieDensite.setObjectName(_fromUtf8("text_nomSortieDensite"))
        self.gridLayout_11.addWidget(self.text_nomSortieDensite, 15, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.tabProperties)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_11.addWidget(self.label_52, 17, 0, 1, 1)
        self.text_inputFichierXYZ = QtGui.QLineEdit(self.tabProperties)
        self.text_inputFichierXYZ.setObjectName(_fromUtf8("text_inputFichierXYZ"))
        self.gridLayout_11.addWidget(self.text_inputFichierXYZ, 17, 1, 1, 1)
        self.boutonInputTxt = QtGui.QPushButton(self.tabProperties)
        self.boutonInputTxt.setObjectName(_fromUtf8("boutonInputTxt"))
        self.gridLayout_11.addWidget(self.boutonInputTxt, 17, 2, 1, 1)
        self.label_53 = QtGui.QLabel(self.tabProperties)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_11.addWidget(self.label_53, 18, 0, 1, 1)
        self.text_inputFichierRXP = QtGui.QLineEdit(self.tabProperties)
        self.text_inputFichierRXP.setObjectName(_fromUtf8("text_inputFichierRXP"))
        self.gridLayout_11.addWidget(self.text_inputFichierRXP, 18, 1, 1, 1)
        self.boutonInputRxp = QtGui.QPushButton(self.tabProperties)
        self.boutonInputRxp.setObjectName(_fromUtf8("boutonInputRxp"))
        self.gridLayout_11.addWidget(self.boutonInputRxp, 18, 2, 1, 1)
        self.label_54 = QtGui.QLabel(self.tabProperties)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_11.addWidget(self.label_54, 19, 0, 1, 1)
        self.text_nomScan = QtGui.QLineEdit(self.tabProperties)
        self.text_nomScan.setText(_fromUtf8(""))
        self.text_nomScan.setObjectName(_fromUtf8("text_nomScan"))
        self.gridLayout_11.addWidget(self.text_nomScan, 19, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.tabProperties)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_11.addWidget(self.label_55, 20, 0, 1, 1)
        self.text_nombreTirs = QtGui.QLineEdit(self.tabProperties)
        self.text_nombreTirs.setObjectName(_fromUtf8("text_nombreTirs"))
        self.gridLayout_11.addWidget(self.text_nombreTirs, 20, 1, 1, 1)
        self.text_nomMaket = QtGui.QLineEdit(self.tabProperties)
        self.text_nomMaket.setText(_fromUtf8(""))
        self.text_nomMaket.setObjectName(_fromUtf8("text_nomMaket"))
        self.gridLayout_11.addWidget(self.text_nomMaket, 16, 1, 1, 1)
        self.label_69 = QtGui.QLabel(self.tabProperties)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_11.addWidget(self.label_69, 21, 0, 1, 1)
        self.boutonExecuter = QtGui.QPushButton(self.tabProperties)
        self.boutonExecuter.setObjectName(_fromUtf8("boutonExecuter"))
        self.gridLayout_11.addWidget(self.boutonExecuter, 22, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.tabProperties)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_11.addWidget(self.label_51, 16, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbox_matSOP = QtGui.QCheckBox(self.tabProperties)
        self.cbox_matSOP.setText(_fromUtf8(""))
        self.cbox_matSOP.setObjectName(_fromUtf8("cbox_matSOP"))
        self.horizontalLayout.addWidget(self.cbox_matSOP)
        self.text_cheminMatSop = QtGui.QLineEdit(self.tabProperties)
        self.text_cheminMatSop.setObjectName(_fromUtf8("text_cheminMatSop"))
        self.horizontalLayout.addWidget(self.text_cheminMatSop)
        self.gridLayout_11.addLayout(self.horizontalLayout, 21, 1, 1, 1)
        self.boutonMatriceSOPSuppl = QtGui.QPushButton(self.tabProperties)
        self.boutonMatriceSOPSuppl.setObjectName(_fromUtf8("boutonMatriceSOPSuppl"))
        self.gridLayout_11.addWidget(self.boutonMatriceSOPSuppl, 21, 2, 1, 1)
        self.combo_box_ponderation = QtGui.QComboBox(self.tabProperties)
        self.combo_box_ponderation.setObjectName(_fromUtf8("combo_box_ponderation"))
        self.combo_box_ponderation.addItem(_fromUtf8(""))
        self.combo_box_ponderation.addItem(_fromUtf8(""))
        self.combo_box_ponderation.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.combo_box_ponderation, 7, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.tabProperties)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_11.addWidget(self.label_70, 7, 0, 1, 1)
        self.label_56 = QtGui.QLabel(self.tabProperties)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_11.addWidget(self.label_56, 14, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.cbox_thetaFiltre = QtGui.QCheckBox(self.tabProperties)
        self.cbox_thetaFiltre.setText(_fromUtf8(""))
        self.cbox_thetaFiltre.setObjectName(_fromUtf8("cbox_thetaFiltre"))
        self.horizontalLayout_18.addWidget(self.cbox_thetaFiltre)
        self.text_tetaMin = QtGui.QLineEdit(self.tabProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_tetaMin.sizePolicy().hasHeightForWidth())
        self.text_tetaMin.setSizePolicy(sizePolicy)
        self.text_tetaMin.setObjectName(_fromUtf8("text_tetaMin"))
        self.horizontalLayout_18.addWidget(self.text_tetaMin)
        self.text_tetaMax = QtGui.QLineEdit(self.tabProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_tetaMax.sizePolicy().hasHeightForWidth())
        self.text_tetaMax.setSizePolicy(sizePolicy)
        self.text_tetaMax.setObjectName(_fromUtf8("text_tetaMax"))
        self.horizontalLayout_18.addWidget(self.text_tetaMax)
        self.gridLayout_11.addLayout(self.horizontalLayout_18, 14, 1, 1, 1)
        self.label_71 = QtGui.QLabel(self.tabProperties)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_11.addWidget(self.label_71, 8, 0, 1, 1)
        self.text_FichierPonderation = QtGui.QLineEdit(self.tabProperties)
        self.text_FichierPonderation.setText(_fromUtf8(""))
        self.text_FichierPonderation.setObjectName(_fromUtf8("text_FichierPonderation"))
        self.gridLayout_11.addWidget(self.text_FichierPonderation, 8, 1, 1, 1)
        self.boutonFichierPonderation = QtGui.QPushButton(self.tabProperties)
        self.boutonFichierPonderation.setObjectName(_fromUtf8("boutonFichierPonderation"))
        self.gridLayout_11.addWidget(self.boutonFichierPonderation, 8, 2, 1, 1)
        self.gridLayout_11.setRowStretch(22, 1)
        self.verticalLayout.addLayout(self.gridLayout_11)
        self.tabPrincipal.addTab(self.tabProperties, _fromUtf8(""))
        self.tabtoolBox = QtGui.QWidget()
        self.tabtoolBox.setObjectName(_fromUtf8("tabtoolBox"))
        self.tabPrincipal.addTab(self.tabtoolBox, _fromUtf8(""))
        self.gridLayout_19.addWidget(self.tabPrincipal, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOuvrir_properties = QtGui.QAction(MainWindow)
        self.actionOuvrir_properties.setObjectName(_fromUtf8("actionOuvrir_properties"))
        self.actionSauvegarder = QtGui.QAction(MainWindow)
        self.actionSauvegarder.setObjectName(_fromUtf8("actionSauvegarder"))
        self.actionSauvegarder_sous = QtGui.QAction(MainWindow)
        self.actionSauvegarder_sous.setObjectName(_fromUtf8("actionSauvegarder_sous"))
        self.actionNouveau_fichier = QtGui.QAction(MainWindow)
        self.actionNouveau_fichier.setObjectName(_fromUtf8("actionNouveau_fichier"))
        self.action_propos = QtGui.QAction(MainWindow)
        self.action_propos.setObjectName(_fromUtf8("action_propos"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionEnregistrer_utilisateur = QtGui.QAction(MainWindow)
        self.actionEnregistrer_utilisateur.setObjectName(_fromUtf8("actionEnregistrer_utilisateur"))
        self.actionExplorer = QtGui.QAction(MainWindow)
        self.actionExplorer.setObjectName(_fromUtf8("actionExplorer"))
        self.menuFichier.addAction(self.actionNouveau_fichier)
        self.menuFichier.addAction(self.actionOuvrir_properties)
        self.menuFichier.addAction(self.actionSauvegarder)
        self.menuFichier.addAction(self.actionSauvegarder_sous)
        self.menuFichier.addAction(self.actionExplorer)
        self.menuOptions.addAction(self.action_propos)
        self.menuOptions.addAction(self.actionDocumentation)
        self.menuOptions.addAction(self.actionEnregistrer_utilisateur)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPrincipal.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Voxelisation IHM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Fichier Log", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Repertoire par defaut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Chemin executable", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonRepertoireDefaut.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonCheminExec.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonLog.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabConfig), QtGui.QApplication.translate("MainWindow", "configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeTypeExtraction.setItemText(0, QtGui.QApplication.translate("MainWindow", "0 : tous les points (format : Nb_echo, direction, longueur)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeTypeExtraction.setItemText(1, QtGui.QApplication.translate("MainWindow", "1: points définis sur zone (format : X, Y, Z, I, dev)", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeScan.setItemText(0, QtGui.QApplication.translate("MainWindow", "0 : tous les scans Riegl du projet", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeScan.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 : un scan Riegl du projet", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeScan.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 : un fichier texte de points", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeScan.setItemText(3, QtGui.QApplication.translate("MainWindow", "3 : un scan Riegl sans projet", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_Mode.setItemText(0, QtGui.QApplication.translate("MainWindow", "0 : generer maille", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_Mode.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 : get min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_Mode.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 : extraire densité fichier Riegl", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_Mode.setItemText(3, QtGui.QApplication.translate("MainWindow", "3 : extraire densité fichier texte", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_Mode.setItemText(4, QtGui.QApplication.translate("MainWindow", "4 : extraire points fichier Riegl", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_Mode.setItemText(5, QtGui.QApplication.translate("MainWindow", "5 : extraire densite fichier texte ALS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Options d\'extraction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Executer sur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "Multi echo ?", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeTypeMultiEcho.setItemText(0, QtGui.QApplication.translate("MainWindow", "0 : tous les echos", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeTypeMultiEcho.setItemText(1, QtGui.QApplication.translate("MainWindow", "1: first return", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_listeTypeMultiEcho.setItemText(2, QtGui.QApplication.translate("MainWindow", "2: last return", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonProjetRiegl.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonDossierOutput.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Type Maillage", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_maillage.setItemText(0, QtGui.QApplication.translate("MainWindow", "0 : maillage Spherique", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_maillage.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 : maillage Cubique", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Résolution", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Resolution.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonverifier.setText(QtGui.QApplication.translate("MainWindow", "verifier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Point Min (XYZ)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Point Max (XYZ)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Dossier output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Dossier Riegl", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Xmin.setText(QtGui.QApplication.translate("MainWindow", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Ymin.setText(QtGui.QApplication.translate("MainWindow", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Zmin.setText(QtGui.QApplication.translate("MainWindow", "-10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Xmax.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Ymax.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.text_Zmax.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "Filtre intensite", None, QtGui.QApplication.UnicodeUTF8))
        self.text_iMin.setText(QtGui.QApplication.translate("MainWindow", "-100", None, QtGui.QApplication.UnicodeUTF8))
        self.text_iMax.setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Filtre deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dMin.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.text_dMax.setText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Nom fichier densite", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Input fichier txt", None, QtGui.QApplication.UnicodeUTF8))
        self.text_inputFichierXYZ.setText(QtGui.QApplication.translate("MainWindow", "exemple.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonInputTxt.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "Input fichier rxp", None, QtGui.QApplication.UnicodeUTF8))
        self.text_inputFichierRXP.setText(QtGui.QApplication.translate("MainWindow", "exemple.rxp", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonInputRxp.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "Nom scan Riegl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Nombre de tir max par fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.text_nombreTirs.setText(QtGui.QApplication.translate("MainWindow", "1000000000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Matrice SOP supplementaire", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonExecuter.setText(QtGui.QApplication.translate("MainWindow", "executer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "Nom fichier DART (option)", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonMatriceSOPSuppl.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_ponderation.setItemText(0, QtGui.QApplication.translate("MainWindow", "0 : pondération par le nombre d\'échos", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_ponderation.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 : pas de pondération", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_box_ponderation.setItemText(2, QtGui.QApplication.translate("MainWindow", "2 : pondération avec fichier de paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "Méthode pondération", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "Filtre Theta (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.text_tetaMin.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.text_tetaMax.setText(QtGui.QApplication.translate("MainWindow", "180", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("MainWindow", "Fichier de pondération", None, QtGui.QApplication.UnicodeUTF8))
        self.boutonFichierPonderation.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabProperties), QtGui.QApplication.translate("MainWindow", "execution", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabtoolBox), QtGui.QApplication.translate("MainWindow", "ToolBox", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "aide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOuvrir_properties.setText(QtGui.QApplication.translate("MainWindow", "ouvrir properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSauvegarder.setText(QtGui.QApplication.translate("MainWindow", "sauvegarder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSauvegarder_sous.setText(QtGui.QApplication.translate("MainWindow", "sauvegarder sous...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNouveau_fichier.setText(QtGui.QApplication.translate("MainWindow", "nouveau fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.action_propos.setText(QtGui.QApplication.translate("MainWindow", "à propos...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer_utilisateur.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer utilisateur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExplorer.setText(QtGui.QApplication.translate("MainWindow", "explorer...", None, QtGui.QApplication.UnicodeUTF8))

