/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_ird_voxelidar_voxelisation_jni_TestJNI1 */

using namespace std;

#include <riegl/scanlib.hpp>

#include "Fast_serializer.h"
#include "puechabonfilter.h"
#include "Params.h"
#include <list>

#include "Shot.h"
#include "ShotComplete.h"
#include "mypointcloud.h"

#ifndef _Included_fr_ird_voxelidar_voxelisation_extraction_RxpExtraction
#define _Included_fr_ird_voxelidar_voxelisation_extraction_RxpExtraction
#ifdef __cplusplus
extern "C" {
#endif

	JNIEXPORT void JNICALL Java_fr_ird_voxelidar_voxelisation_extraction_RxpExtraction_afficherBonjour
		(JNIEnv *, jobject);

	JNIEXPORT bool JNICALL Java_fr_ird_voxelidar_voxelisation_extraction_RxpExtraction_simpleExtraction
		(JNIEnv *, jobject, jstring fileName, jobject shots);





#ifdef __cplusplus
}
#endif
#endif
