/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ird.voxelidargui.swing;

import fr.ird.voxelidar.engine3d.math.matrix.Mat4D;

/**
 *
 * @author Julien
 */
public class JFrameMatrix extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMatrix
     */
    
    private Mat4D matrix;
    
    public JFrameMatrix(Mat4D matrix) {
        
        initComponents();
        
        this.matrix = matrix;
        
        double mat4x4[] = matrix.mat;

        jTextFieldMat11.setText(String.valueOf(mat4x4[0]));
        jTextFieldMat12.setText(String.valueOf(mat4x4[1]));
        jTextFieldMat13.setText(String.valueOf(mat4x4[2]));
        jTextFieldMat14.setText(String.valueOf(mat4x4[3]));
        jTextFieldMat21.setText(String.valueOf(mat4x4[4]));
        jTextFieldMat22.setText(String.valueOf(mat4x4[5]));
        jTextFieldMat23.setText(String.valueOf(mat4x4[6]));
        jTextFieldMat24.setText(String.valueOf(mat4x4[7]));
        jTextFieldMat31.setText(String.valueOf(mat4x4[8]));
        jTextFieldMat32.setText(String.valueOf(mat4x4[9]));
        jTextFieldMat33.setText(String.valueOf(mat4x4[10]));
        jTextFieldMat34.setText(String.valueOf(mat4x4[11]));
        jTextFieldMat41.setText(String.valueOf(mat4x4[12]));
        jTextFieldMat42.setText(String.valueOf(mat4x4[13]));
        jTextFieldMat43.setText(String.valueOf(mat4x4[14]));
        jTextFieldMat44.setText(String.valueOf(mat4x4[15]));
    }

    public Mat4D getMatrix() {
        
        matrix.mat = new double[]{
            
            Double.valueOf(jTextFieldMat11.getText()),
            Double.valueOf(jTextFieldMat12.getText()),
            Double.valueOf(jTextFieldMat13.getText()),
            Double.valueOf(jTextFieldMat14.getText()),
            Double.valueOf(jTextFieldMat21.getText()),
            Double.valueOf(jTextFieldMat22.getText()),
            Double.valueOf(jTextFieldMat23.getText()),
            Double.valueOf(jTextFieldMat24.getText()),
            Double.valueOf(jTextFieldMat31.getText()),
            Double.valueOf(jTextFieldMat32.getText()),
            Double.valueOf(jTextFieldMat33.getText()),
            Double.valueOf(jTextFieldMat34.getText()),
            Double.valueOf(jTextFieldMat41.getText()),
            Double.valueOf(jTextFieldMat42.getText()),
            Double.valueOf(jTextFieldMat43.getText()),
            Double.valueOf(jTextFieldMat44.getText())
        };
        
        return matrix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jTextFieldMat11 = new javax.swing.JTextField();
        jTextFieldMat13 = new javax.swing.JTextField();
        jTextFieldMat14 = new javax.swing.JTextField();
        jTextFieldMat12 = new javax.swing.JTextField();
        jTextFieldMat24 = new javax.swing.JTextField();
        jTextFieldMat23 = new javax.swing.JTextField();
        jTextFieldMat22 = new javax.swing.JTextField();
        jTextFieldMat21 = new javax.swing.JTextField();
        jTextFieldMat34 = new javax.swing.JTextField();
        jTextFieldMat33 = new javax.swing.JTextField();
        jTextFieldMat32 = new javax.swing.JTextField();
        jTextFieldMat31 = new javax.swing.JTextField();
        jTextFieldMat44 = new javax.swing.JTextField();
        jTextFieldMat43 = new javax.swing.JTextField();
        jTextFieldMat42 = new javax.swing.JTextField();
        jTextFieldMat41 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Matrix");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jTextFieldMat43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMat44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMat11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMat21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMat31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMat41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMat42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel19;
    private javax.swing.JTextField jTextFieldMat11;
    private javax.swing.JTextField jTextFieldMat12;
    private javax.swing.JTextField jTextFieldMat13;
    private javax.swing.JTextField jTextFieldMat14;
    private javax.swing.JTextField jTextFieldMat21;
    private javax.swing.JTextField jTextFieldMat22;
    private javax.swing.JTextField jTextFieldMat23;
    private javax.swing.JTextField jTextFieldMat24;
    private javax.swing.JTextField jTextFieldMat31;
    private javax.swing.JTextField jTextFieldMat32;
    private javax.swing.JTextField jTextFieldMat33;
    private javax.swing.JTextField jTextFieldMat34;
    private javax.swing.JTextField jTextFieldMat41;
    private javax.swing.JTextField jTextFieldMat42;
    private javax.swing.JTextField jTextFieldMat43;
    private javax.swing.JTextField jTextFieldMat44;
    // End of variables declaration//GEN-END:variables
}
