#ifndef LASZIPLIBRARY_GLOBAL_H
#define LASZIPLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LASZIPLIBRARY_LIBRARY)
#  define LASZIPLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LASZIPLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LASZIPLIBRARY_GLOBAL_H
